<a href="https://colab.research.google.com/github/AdegaxX/PROGRAMACAO/blob/main/Novo_Coiso.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
x = ['a', 'b', 'c']
y = list(x)
y[1] = 'z'
print(x)
print(y)

['a', 'b', 'c']
['a', 'z', 'c']


In [ ]:
fam = [1.56, 1.75, 1.80, 1.68]
max(fam) # Uma função que exibe o maior valor de um elemento

1.8

In [ ]:
print(round(1.70, 1)) # Arredonda os valores
print(round(2.45)) # Arredonda deixando somente em inteiro

1.7
2


In [ ]:
help(round) # O 'help()' mostra para que a função é usada

Help on built-in function round in module builtins:

round(number, ndigits=None)
    Round a number to a given precision in decimal digits.
    
    The return value is an integer if ndigits is omitted or None.  Otherwise
    the return value has the same type as the number.  ndigits may be negative.



In [ ]:
var1 = [1, 2, 3, 4]
var2 = True

print(type(var1))
print(len(var1)) # Mostra o tamanho da variável 'var1'
out2 = int(var2)
print(out2)

<class 'list'>
4
1


In [ ]:
first = [11.25, 18.0, 20.0]
second = [10.75, 9.50]

full = first + second # Concatenação das duas listas 'first' e 'second'
print(full)

full_sorted = sorted(full, reverse = True) # "sorted()" coloca um elemento, como uma lista, em ordem crescente ou decrescente utilizando o 'reverse = True' (para decrescente) e 'reverse = False' (para crescente)
print(full_sorted)

full_sorted2 = sorted(full) # Para deixar o "sorted" em forma crescente, não precisa utilizar o 'reverse = False', basta deixar em branco
print(full_sorted2)

[11.25, 18.0, 20.0, 10.75, 9.5]
[20.0, 18.0, 11.25, 10.75, 9.5]
[9.5, 10.75, 11.25, 18.0, 20.0]


In [ ]:
listA = ['Pai', 1.68, 'Pai', 1.70, 'mãe', 1.65, 'irmã', 1.70]

print(listA.index('Pai')) # Mostra a localização do elemento na lista

print(listA.count(1.70)) # Verifica quantos elementos repetidos tem na lista
print(listA.count('Pai'))
print(listA.count('irmão'))

0
2
2
0


In [ ]:
listA = ['Pai', 1.68, 'Pai', 1.70, 'mãe', 1.65, 'irmã', 1.70]

listA.append('irmão') # Adiciona um elemento no fim da lista/variável
listA.append(1.75)
print(listA)

['Pai', 1.68, 'Pai', 1.7, 'mãe', 1.65, 'irmã', 1.7, 'irmão', 1.75]


In [ ]:
sister = 'liz'

print(sister.capitalize()) # Coloca o elemento da variável 'sister' com letra maiúscula

print(sister.replace('z', 'sa')) # Altera o 'z' pelo 'sa' no elemento da variável 'sister'

Liz
lisa


In [ ]:
place = 'Poolhouse'
print(place)
place_up = place.upper()

print(place_up)

print(place.count('o'))

Poolhouse
POOLHOUSE
3


In [ ]:
# 4) Na linha 5 print o index que contém o número 20 com o método index().
are = [11.25, 18.0, 20.0, 10.75, 9.50]
print(are.index(20.0))

2


In [ ]:
# 5) Usando o método count(), mostre via print o número de vezes que 9.50 aparece na lista.
are = are = [11.25, 18.0, 20.0, 10.75, 9.50]
print(are.count(9.50))

1


In [ ]:
pip install numpy

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
pip install pydicom

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.0/2.0 MB 45.6 MB/s eta 0:00:00


In [ ]:
import numpy
array([1, 2, 3])

NameError: ignored

In [ ]:
import numpy # Biblioteca de matrizes e vetores
numpy.array([1, 2, 3])

array([1, 2, 3])

In [ ]:
import numpy as np # Importou a biblioteca 'numpy' para 'np'
np.array([1, 2, 3])

array([1, 2, 3])

In [ ]:
from numpy import array # da biblioteca 'numpy' importe somente 'array'
array([1, 2, 3])

array([1, 2, 3])

In [ ]:
import numpy as np

fam = ('Liz', 1.73, 'Emma', 1.68, 'mom', 1.71, 'dad', 1.89)
print(fam)
print(type(fam))

fam_ext = fam + ('we', 1.79)
print(fam_ext)
print(type(fam_ext))

print(str(len(fam_ext)) + " elements is fam_ext")
print(type(str(len(fam_ext)) + " elements is fam_ext"))

np_fam = np.array(fam_ext)

('Liz', 1.73, 'Emma', 1.68, 'mom', 1.71, 'dad', 1.89)
<class 'tuple'>
('Liz', 1.73, 'Emma', 1.68, 'mom', 1.71, 'dad', 1.89, 'we', 1.79)
<class 'tuple'>
10 elements is fam_ext
<class 'str'>


In [ ]:
r = 0.43
import math
C = 2 * math.pi * r
print('Circunferência: ' + str(C))
print(type(C))
A = 2 * math.pi * r ** 2
print('Área: ' + str(A))
print(type(A))

Circunferência: 2.701769682087222
<class 'float'>
Área: 1.1617609632975054
<class 'float'>


In [ ]:
alt = [2.1, 2.2, 2.3, 2.4, 2.5]
lar = [3.1, 3.2, 3.3, 3.4, 3.5]

print((alt / lar) ** 2) # Só é possível usar o 'numpy' para trabalhar com as listas.

TypeError: ignored

In [ ]:
import numpy as np
alt = [2.1, 2.2, 2.3, 2.4, 2.5]
lar = [3.1, 3.2, 3.3, 3.4, 3.5]
np_alt = np.array(alt)
np_lar = np.array(lar)

bmi = np_alt / (np_lar ** 2)
print(bmi)
print(type(bmi))

[0.21852237 0.21484375 0.21120294 0.20761246 0.20408163]
<class 'numpy.ndarray'>


In [ ]:
list1 = [1, 2, 3]
list2 = [1, 2, 3]

somlist = list1 + list2 # Sem usar o 'array' a soma irá somente unir os valores, como uma concatenação
print(somlist)

[1, 2, 3, 1, 2, 3]


In [ ]:
import numpy as ls
list1 = [1, 2, 3]
list2 = [1, 2, 3]

list_ls1 = ls.array(list1)
list_ls2 = ls.array(list2)

som_list = list_ls1 + list_ls2 # Usando o 'array' (numpy) a soma irá somar os elementos separadamente
print(som_list)

[2 4 6]


In [ ]:
import numpy as np
bm = [20, 22, 24, 26, 28, 30]
bm_new = np.array(bm)

print(bm_new[1]) # Mostra exatamente qual o elemento está no array/lista
print(bm_new > 23)
print(bm_new < 20)

22
[False False  True  True  True  True]
[False False False False False False]
